# Welcome to Jekyll!
# Site settings
title: "Lbkinging's Blog"  # åšå®¢æ ‡é¢˜
author: "Lbkinging"        # ä½œè€…åç§°
email: "lbkinging@example.com"  # ä½ çš„é‚®ç®±åœ°å€
description: "A blog by a retired red teamer exploring the world of blue teams."  
baseurl: "/"  # å­è·¯å¾„ï¼ˆå¦‚é€‚ç”¨ï¼‰
url: ""  # ç«™ç‚¹çš„æ ¹è·¯å¾„åœ°å€ï¼ˆç”Ÿäº§ç¯å¢ƒéœ€è¦å¡«å†™å®Œæ•´ URLï¼‰

# ------------------------------------------------------------------------------
# Custom settings
# ------------------------------------------------------------------------------
# Useful links
github_username: "lbkinging"    # GitHub ç”¨æˆ·å
facebook_username: "lbkinging" # Facebook ç”¨æˆ·åï¼ˆå¦‚é€‚ç”¨ï¼‰
twitter_username: "lbkinging"  # Twitter ç”¨æˆ·åï¼ˆå¦‚é€‚ç”¨ï¼‰
linkedin_id: "lbkinging"       # LinkedIn ç”¨æˆ· IDï¼ˆå¦‚é€‚ç”¨ï¼‰

# Theme
# theme: jekyll-theme-potato-hacker           # å¯ç”¨ä¸»é¢˜
theme_repository: "https://github.com/luxedo/jekyll-theme-potato-hacker"  
theme_base: "dark"       # é»˜è®¤ä¸»é¢˜é¢œè‰² (light | dark)
theme_switch: on         # æ˜¯å¦å¯ç”¨é¢œè‰²åˆ‡æ¢åŠŸèƒ½ (on | off)

# Extra settings
blog: off                 # å¯ç”¨åšå®¢æ ‡ç­¾å’Œæ–‡ç« åˆ—è¡¨
recent_posts: 5
avatar: on               # æ˜¾ç¤ºå¤´åƒ
avatar_image: "assets/img/lb.png"  # å¤´åƒå›¾ç‰‡è·¯å¾„
avatar_description: "Lbkinging , ä¸€ä¸ªçƒ­çˆ±æŠ€æœ¯çš„æŠ€æœ¯äººğŸ˜„"
highlighter_theme: gruvbox  # ä»£ç é«˜äº®ä¸»é¢˜
toolbar_priority:        # å·¥å…·æ é¡¹ç›®é¡ºåº
  - Home
  - blog_type
  - Blog
  - About

# Collections
collections:
  blog_type:
    output: true
  items:
    output: true

# ------------------------------------------------------------------------------
# Build settings
excerpt_separator: "<!--more-->"  # ç”¨äºæ–‡ç« æ‘˜è¦çš„åˆ†éš”ç¬¦
markdown: kramdown                # Markdown å¼•æ“
highlighter: rouge                # ä»£ç é«˜äº®å¼•æ“
kramdown:
  input: GFM                      # æ”¯æŒ GitHub é£æ ¼ Markdown
  syntax_highlighter: rouge
exclude:
  - Gemfile.lock'
  - Gemfile
